Tests 101
ccims/issue-creator pull request #8
Opened 2020-08-21 16:24 UTC by Jacky20000

## Preparations
Please check if the PR fulfills these requirements
- [ ] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [ ] Das Feature ist dokumentiert
- [ ] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description
SLADIM-101

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
logs were received and saved in the database

* **What is the new behavior (if this is a feature change)?**
issue is created and reported to the backend mockup. Issue ID is assigned to the logmessage and saved in the database.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
The 'Logs' class was changed and a issueID was added. Function 'handleLogMessage' in logreceiver behaves differently now.

* **Other information**:
-

## :lock: Closes
Which issue(s) is (are) being closed by the PR?
-

2020-08-24 13:33 UTC, stiesssh commented
bevor ich mit dem eigentlichen review fortfahre: 
die klassen `cb-open-issue-creator.ts`, `error-response-issue-creator.ts`, `timeout-issue-creator.ts` und `cpu-issue-creator.ts` sind bis auf eine code zeile und clone. 
refactored das bitte, z.B. in dem ihr die identischen codeabschnitte in eine methode in einer geteilten oberklasse auslagert. 

theoretisch haben die klassen mit `IssueReporter` bereits eine gemeinsame oberklasse, semantisch ist dies jedoch nicht der richtige ort, daher würde ich eine weiter klasse in die hierarchie einfügen.

dann habt ihr zwar eine klasse mehr, aber solltet ihr jemals etwas am IssueFormat oder am LogMessageFormat ändern, dann müsst ihr es nur an _einer_ stelle ändern und nicht an vieren.

2020-08-24 13:48 UTC, stiesssh requested changes

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> + */
wie ich mir den code so anschaue, erbt die klasse von 'issueReporter', nicht von 'IssueComponent.

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +   * @param log received log in the LogMessageFormat
missing blank line.
it's 'cb', isn't it?
also, no need to state that log is of type LogMessageFormat, one glance at the method signature and you know the type.
```suggestion
   * handles cb open logs, no specific information on how to handle cpu issues yet
   *
   * @param log the received log
```

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +   * @returns the issue ID received from the Back end
```suggestion
   * @returns the issue ID received from the backend
```

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/cpu-issue-creator.ts
>   * CpuUtilizationIssueComponent handles CpuUtilization Logs, it extends IssueComponent to enable individual issue creation for cpu issues
s.o.
```suggestion
 * CpuUtilizationIssueComponent handles CpuUtilization Logs, it extends IssueReporter to enable individual issue creation for cpu issues
```

2020-08-24 13:48 UTC, stiesssh commented on src/IssueFormat.ts
> + */
wer sind diese ominösen 'backend developers'? 
was ist 'Sandro's API'? 

besser wäre, wenn ihr links zu den jeweiligen repos oder die korrekten namen der jeweiligen projekte verwendent.

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +    return this.id;
code clone. diesen teil würde ich als methode `createIssueFromLog` oder so ähnlich einen gemeinsame elternklasse auslagern, und an dieser stelle nur noch die geerbte methode aufrufen.

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/issue-reporter.ts
> +  api = 'http://localhost:8080/api';
keine hardcoded urls. verwendet euer .env!

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/issue-reporter.ts
> +   */
wrong usage of tags!!!

```suggestion
  /**
   * sends an Issues to the current MockApi and receives the Issue ID.
   * can be called in every Component that extends IssueComponent.
   *
   * @param issue the issue to be send
   * @returns the issueID received when the the request was accepted by the server
   */
```

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/issue-reporter.ts
> +   * Can be called in every Component that extends IssueComponent.
es gibt keine klasse `IssueComponent` ??

2020-08-24 13:48 UTC, stiesssh commented on src/issue-creator/issue-reporter.ts
> +
too many blank lines.

2020-08-24 14:03 UTC, stiesssh requested changes
sorry, hab zwischen durch zu früh auf 'submit review' geklickt :x 

bitte comments aus beiden reviews einarbeiten. und am besten mit meiner ersten anmerkung, bezüglich dem ändern der klassen hierarchie, anfangen.

2020-08-24 14:03 UTC, stiesssh commented on src/log-receiver/log-receiver.service.ts
> -
eignetlich war die leerzeile hier ganz gut. sie war der leserlichkeit zuträglich.

2020-08-24 14:03 UTC, stiesssh commented on src/log-receiver/log-receiver.service.ts
> +   *
wrong order of lines. correct order is short description + blank line, more detailed description +  blank line (may be omitted if not necessary), tags.
```suggestion
   * 
   * @param logMessage is the log received by the log receiver controller
   * @returns issueID that was received from the backend
```

2020-08-24 14:03 UTC, stiesssh commented on src/log-receiver/log-receiver.service.ts
>     * Handling of Log messages
put more info into short description to omit long description. this does not apply every where, but in this case it works, i guess.
```suggestion
   * Handles Log messages by delegating them to the respective IssueCreator
```

2020-08-24 14:03 UTC, stiesssh commented on src/log-receiver/log-receiver.service.ts
> +   * Writes the received log message into the database together with the issue ID
improve wording.
```suggestion
   * Writes the received log message and the issue ID into the database
```

2020-08-24 14:03 UTC, stiesssh commented on src/log-receiver/log-receiver.service.ts
>     * @param logMessage Log sent by the monitor
@returns tag fehlt

2020-08-24 14:03 UTC, stiesssh commented on src/log-receiver/log-receiver.service.ts
> -   * @returns all logs from the database
das @returns hat da schon hingehört.

2020-08-25 08:25 UTC, stiesssh requested changes

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +}
@Jacky20000 ich glaube, du hast das konzept der vererbung nicht verstanden. ich empfehle dir, dich nochmal mit den PSE unterlagen auseinander zusetzen.

das tolle an vererbung ist schließlich, dass kinder die methoden und eigentschaften ihrere eltern erben - auch in typescript ([https://www.typescriptlang.org/docs/handbook/classes.html#inheritance](https://www.typescriptlang.org/docs/handbook/classes.html#inheritance))

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +    return this.issueCreator.createIssueFromLog(log);
```suggestion
    return this.createIssueFromLog(log);
```

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +    this.issueCreator = new IssueCreator(http, configService);
```suggestion
```

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +  issueCreator: IssueCreator;
```suggestion
```

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +   * handles cp open logs by creating an Issue and sending it to the API: https://github.com/ccims/ccims-backend/tree/apiMockup
das sollte cb für **c**ircuit **b**reaker sein, oder?
```suggestion
   * handles cb open logs by creating an Issue and sending it to the API: https://github.com/ccims/ccims-backend/tree/apiMockup
```

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/cpu-issue-creator.ts
> +}
siehe cb-issue-creator. bitte die dort genannten änderung auch hier anwenden.

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/error-response-issue-creator.ts
> +}
siehe cb-issue-creator. bitte die dort genannten änderung auch hier anwenden.

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/issue-creator.ts
> + */
```suggestion
 * generic IssueCreator class. It extends IssueReporter to report issues that were created.
 * It implements the IssueCreatorComponent to handle the incoming logs.
 */
```
...zumindest, wenn du sagen will, dass 'erzeugte issues reported werden' .
außerdem machen sich satzzeichen im allgemeinen echt gut ;)

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/issue-reporter.ts
> + * Provides the basic functionality every "detailed" IssueComponent should have
hier ist die rede von den IssueCreators, oder?
```suggestion
 * Provides the basic functionality every "detailed" IssueCreator should have
```

2020-08-25 08:25 UTC, stiesssh commented on src/issue-creator/timeout-issue-creator.ts
> +}
siehe cb-issue-creator. bitte die dort genannten änderung auch hier anwenden.

2020-08-25 08:31 UTC, Jacky20000 commented on src/issue-creator/cb-open-issue-creator.ts
> +   * handles cp open logs by creating an Issue and sending it to the API: https://github.com/ccims/ccims-backend/tree/apiMockup
Ja cb steht für circuit breaker

2020-08-25 09:16 UTC, stiesssh commented on src/issue-creator/cb-open-issue-creator.ts
> +}
hierüber bitte noch nachdenken und meinen vorschlag entweder einarbeiten, oder begründen warum es ein doofer vorschlag ist.

2020-08-25 09:26 UTC, stiesssh approved these changes

2020-08-25 09:56 UTC, merged